In [1]:
from importlib.metadata import version

# 2. working with text data

## load raw text dataset and split the text into tokens

In [6]:
with open('the-verdict.txt', 'r', encoding='utf-8') as f:
  raw_text = f.read()

In [7]:
raw_text[:1000]  # Display the first 1000 characters

'I HAD always thought Jack Gisburn rather a cheap genius--though a good fellow enough--so it was no great surprise to me to hear that, in the height of his glory, he had dropped his painting, married a rich widow, and established himself in a villa on the Riviera. (Though I rather thought it would have been Rome or Florence.)\n\n"The height of his glory"--that was what the women called it. I can hear Mrs. Gideon Thwing--his last Chicago sitter--deploring his unaccountable abdication. "Of course it\'s going to send the value of my picture \'way up; but I don\'t think of that, Mr. Rickham--the loss to Arrt is all I think of." The word, on Mrs. Thwing\'s lips, multiplied its _rs_ as though they were reflected in an endless vista of mirrors. And it was not only the Mrs. Thwings who mourned. Had not the exquisite Hermia Croft, at the last Grafton Gallery show, stopped me before Gisburn\'s "Moon-dancers" to say, with tears in her eyes: "We shall not look upon its like again"?\n\nWell!--even 

In [8]:
len(raw_text)  # Display the length of the text (counting characters) to confirm it has been loaded correctly

20479

Split the text into tokens based on punctuation and whitespace

In [ ]:
import re
text = 'Hello, world. This, is a test.'
result = re.split(r'(\s)', text) # Split on whitespace, keeping the delimiters (whitespace) in the result
result

['Hello,', ' ', 'world.', ' ', 'This,', ' ', 'is', ' ', 'a', ' ', 'test.']

In [10]:
# Split the text into words, keeping the delimiters (punctuation and whitespace)
result = re.split(r'([,.:;?_!"()\']|--|\s)', raw_text) 
result = [item.strip() for item in result if item.strip()] # Remove empty strings and strip whitespace
# print(result)
preprocessed = result

In [11]:
len(preprocessed)  # Display the length of the preprocessed text (counting tokens) to confirm it has been processed correctly

4690

In [12]:
preprocessed[:10]  # Display the first 10 tokens to verify preprocessing

['I',
 'HAD',
 'always',
 'thought',
 'Jack',
 'Gisburn',
 'rather',
 'a',
 'cheap',
 'genius']

## converting tokens into token IDs

first build a vocabulary from the preprocessed text

In [13]:
all_words = set(preprocessed)  # Display the unique tokens in the preprocessed text

In [14]:
vocab_size = len(all_words)
print(vocab_size)  # Display the size of the vocabulary

1130


In [15]:
vocab = {token:integer for integer, token in enumerate(all_words)}

In [ ]:
# print the first 10 items of vocab 
for index, item in enumerate(list(vocab.items())[:10]):
  print(item)

In [ ]:
class SimpleTokenizerV1:
  def __init__(self, vocab):
    self.str_to_int = vocab # {str:int}
    self.int_to_str = {i:s for s, i in vocab.items()} # {int:str}
  
  def encode(self, text):
    preprocessed = re.split(r'([,.:;?_!"()\']|--|\s)', text)
    
    preprocessed = [
      item.strip() for item in preprocessed if item.strip()
    ] # Remove empty strings
    ids = [self.str_to_int[s] for s in preprocessed]
    return ids 

  def decode(self, ids):
    text = " ".join([self.int_to_str[i] for i in ids])
    # replace spaces before the specified punctuations
    text = re.sub(r'\s+([,.?!"()\'])', r'\1', text)
    return text


In [ ]:
tokenizer = SimpleTokenizerV1(vocab)

In [ ]:
# example 
text = """"It's the last he painted, you know,"
    Mrs. Gisburn said with pardonable pride."""
ids = tokenizer.encode(text)
print(ids)

In [ ]:
# decode 
tokenizer.decode(ids)

## adding special context tokens

the vocabulary is limited, e.g. it does not contain 'hello' and cannot tokenize the following simple sentence 

In [ ]:
# e.g. Hello is not in the vocabulary 
text = "Hello, do you like tea. is this-- a test?"
tokenizer.decode(tokenizer.encode(text))


expand the vocabulary with special tokens

In [ ]:

all_tokens = sorted(list(set(preprocessed)))
all_tokens.extend(["<|enoftext|>", "<|unk|>"]) 

vocab = {token:integer for integer, token in enumerate(all_tokens)}

In [ ]:
len(vocab.items()) # it now has two more tokens "<|enoftext|>", "<|unk|>"

In [ ]:
for i, item in enumerate(list(vocab.items())[-5:]):
  print(item)

In [ ]:
class SimpleTokenizerV2:
  def __init__(self, vocab):
    self.str_to_int = vocab # {str:int}
    self.int_to_str = {i:s for s, i in vocab.items()} # {int:str}
  
  def encode(self, text):
    preprocessed = re.split(r'([,.:;?_!"()\']|--|\s)', text)
    
    preprocessed = [
      item.strip() for item in preprocessed if item.strip()
    ] # Remove empty strings
    preprocessed = [
      item if item in self.str_to_int
      else "<|unk|>" for item in preprocessed
    ]
    ids = [self.str_to_int[s] for s in preprocessed]
    return ids 

  def decode(self, ids):
    text = " ".join([self.int_to_str[i] for i in ids])
    # replace spaces before the specified punctuations
    text = re.sub(r'\s+([,.?!"()\'])', r'\1', text)
    return text


In [ ]:
tokenizer = SimpleTokenizerV2(vocab)
tokenizer.encode(text)

In [ ]:
text

In [ ]:
tokenizer.decode(tokenizer.encode(text))

## 2.5 byte pair encoding (BPE)

implementing BPE can be relatively complicated;

we will use the existing Python library called [tiktoken](https://github.com/openai/tiktoken), which implements BPE very efficiently  

In [ ]:
# !pip install tiktoken

In [9]:
import tiktoken 

In [10]:
tokenizer = tiktoken.get_encoding('gpt2')

In [12]:
# test tiktoken
text = (
  "Hello, do you like tea? <|endoftext|> in the sunlit terraces"
  "of someunkownPlace."
)

integers = tokenizer.encode(text, allowed_special={"<|endoftext|>"})
print(integers)

[15496, 11, 466, 345, 588, 8887, 30, 220, 50256, 287, 262, 4252, 18250, 8812, 2114, 1659, 617, 2954, 593, 27271, 13]


In [13]:
strings = tokenizer.decode(integers)
print(strings)

Hello, do you like tea? <|endoftext|> in the sunlit terracesof someunkownPlace.


how does BPE tokenizer encodes and decodes the unknown word "unknownPlace" correctly? 

* the algorithm underlying BPE breaks down words that aren't in its predefined vocabulary into smaller subword units or even individual characters, enabling it to handle out-of-vocabulary words

## 2.6 data sampling with a sliding window

generate input-target pairs for LLM training

In [3]:
import tiktoken

with open("the-verdict.txt", "r", encoding="utf-8") as f:
    raw_text = f.read()

tokenizer = tiktoken.get_encoding('gpt2')
enc_text = tokenizer.encode(raw_text)
print(len(enc_text))

# remove first 50 tokens for demon purposes
enc_example = enc_text[50:]

context_size = 4
x = enc_example[:context_size]
y = enc_example[1:context_size+1]
print(f"x: {x}")
print(f"y:      {y}")

for i in range(1, context_size+1):
    context = enc_example[:i]
    desired = enc_example[i]
    print(f"Context: {context} -> Desired: {desired}")

for i in range(1, context_size+1):
    context = enc_example[:i]
    desired = enc_example[i]
    print(tokenizer.decode(context), "->", tokenizer.decode([desired]))

5145
x: [290, 4920, 2241, 287]
y:      [4920, 2241, 287, 257]
Context: [290] -> Desired: 4920
Context: [290, 4920] -> Desired: 2241
Context: [290, 4920, 2241] -> Desired: 287
Context: [290, 4920, 2241, 287] -> Desired: 257
 and ->  established
 and established ->  himself
 and established himself ->  in
 and established himself in ->  a


In [2]:
import tiktoken
import torch 
from torch.utils.data import Dataset, DataLoader

tokenizer = tiktoken.get_encoding('gpt2')

class GPTDatasetV1(Dataset):
  def __init__(self, txt, tokenizer, max_length, stride):
    self.input_ids = []
    self.target_ids = []

    token_ids = tokenizer.encode(txt)

    for i in range(0, len(token_ids) - max_length, stride):
      input_chunk = token_ids[i:i+max_length]
      target_chunk = token_ids[i+1:i+max_length+1]

      self.input_ids.append(torch.tensor(input_chunk))
      self.target_ids.append(torch.tensor(target_chunk))

  def __len__(self):
    return len(self.input_ids)
  
  def __getitem__(self, idx):
    return self.input_ids[idx], self.target_ids[idx]
  

def create_dataloader_v1(txt, batch_size=4, max_length=256,
                         stride=128, shuffle=True, drop_last=True,
                         num_workers=0) -> DataLoader:
        tokenizer = tiktoken.get_encoding('gpt2')
        dataset = GPTDatasetV1(txt, tokenizer, max_length, stride)
        dataloader = DataLoader(
                dataset, 
                batch_size=batch_size,
                shuffle=shuffle,
                drop_last=drop_last,  
                num_workers=num_workers
        )
        return dataloader

with open('the-verdict.txt', 'r', encoding='utf-8') as f:
  raw_text = f.read()

dataloader = create_dataloader_v1(
  raw_text, batch_size=1, max_length=4, stride=1, shuffle=False, 
  # drop_last=True, num_workers=0
)
data_iter = iter(dataloader)
first_batch = next(data_iter)
print(first_batch)

second_batch = next(data_iter)
print(second_batch)

[tensor([[  40,  367, 2885, 1464]]), tensor([[ 367, 2885, 1464, 1807]])]
[tensor([[ 367, 2885, 1464, 1807]]), tensor([[2885, 1464, 1807, 3619]])]


In [3]:
# use the data loader to sample with a batch size greather than 1
dataloader = create_dataloader_v1(
  raw_text, batch_size=8, max_length=4, stride=4, 
  shuffle=False
)
data_iter = iter(dataloader)
inputs, targets = next(data_iter)
print('inputs:\n', inputs)
print('targets:\n', targets)

inputs:
 tensor([[   40,   367,  2885,  1464],
        [ 1807,  3619,   402,   271],
        [10899,  2138,   257,  7026],
        [15632,   438,  2016,   257],
        [  922,  5891,  1576,   438],
        [  568,   340,   373,   645],
        [ 1049,  5975,   284,   502],
        [  284,  3285,   326,    11]])
targets:
 tensor([[  367,  2885,  1464,  1807],
        [ 3619,   402,   271, 10899],
        [ 2138,   257,  7026, 15632],
        [  438,  2016,   257,   922],
        [ 5891,  1576,   438,   568],
        [  340,   373,   645,  1049],
        [ 5975,   284,   502,   284],
        [ 3285,   326,    11,   287]])


In [4]:
torch

<module 'torch' from '/opt/anaconda3/lib/python3.12/site-packages/torch/__init__.py'>

## 2.7 creating token embedding

In [5]:
vocab_size = 6
output_dim = 3
torch.manual_seed(123)
embedding_layer = torch.nn.Embedding(vocab_size, output_dim)
print(embedding_layer.weight)

Parameter containing:
tensor([[ 0.3374, -0.1778, -0.1690],
        [ 0.9178,  1.5810,  1.3010],
        [ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-1.1589,  0.3255, -0.6315],
        [-2.8400, -0.7849, -1.4096]], requires_grad=True)


In [6]:
input_ids = torch.tensor([2, 3, 5, 1])
print(embedding_layer(input_ids))

tensor([[ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-2.8400, -0.7849, -1.4096],
        [ 0.9178,  1.5810,  1.3010]], grad_fn=<EmbeddingBackward0>)


## 2.8 encoding word postions

In [12]:
# use more realistic embedding sizes and vocab sizes
vocab_size = 50257
output_dim = 256
token_embedding_layer = torch.nn.Embedding(vocab_size, output_dim)

# instantiate dataloader
max_length = 4
dataloader = create_dataloader_v1(
  raw_text, batch_size=8, max_length=max_length, stride=max_length, 
  shuffle=False
)

In [11]:
token_embedding_layer.weight

Parameter containing:
tensor([[-2.1338,  1.0524, -0.3885,  ...,  0.2461,  1.2119,  0.3171],
        [ 1.2277, -0.4297, -2.2121,  ..., -0.1640, -0.3348, -0.0221],
        [ 1.3382,  0.2706,  0.5071,  ...,  0.0175, -2.1517,  0.3924],
        ...,
        [-1.4889, -1.2456,  1.8034,  ..., -0.6392, -1.4939,  0.3614],
        [-1.0703,  0.2795, -0.2637,  ..., -0.2810, -1.4755, -0.1183],
        [-0.0071,  0.4982, -0.3319,  ...,  0.4970,  0.9365, -0.2091]],
       requires_grad=True)

# 3. coding attention mechanisms

## simple self-attention mechanism without trainable weights

In [17]:
""" 
calculate context vector for each token embedding in the input sequence
- dot product of query and key, then apply softmax to get attention weights
- context vector: weighted sum of value vectors using attention weights 
"""
# example: your journey starts with one step

import torch
inputs = torch.tensor(
  [[0.43, 0.15, 0.89], # Your     (x^1)
   [0.55, 0.87, 0.66], # journey  (x^2)
   [0.57, 0.85, 0.64], # starts   (x^3)
   [0.22, 0.58, 0.33], # with     (x^4)
   [0.77, 0.25, 0.10], # one      (x^5)
   [0.05, 0.80, 0.55]] # step     (x^6)
)

In [12]:
inputs.shape[1]

3

In [4]:
query = inputs[1]
query

tensor([0.5500, 0.8700, 0.6600])

## self-attention with trainable weights

In [15]:
import torch.nn as nn

class SelfAttention_v1(nn.Module):
  def __init__(self, d_in, d_out):
    super().__init__()
    self.W_query = nn.Parameter(torch.rand(d_in, d_out))
    self.W_key = nn.Parameter(torch.rand(d_in, d_out))
    self.W_value = nn.Parameter(torch.rand(d_in, d_out))

  def forward(self, x):
    keys = x @ self.W_key
    queries = x @ self.W_query
    values = x @ self.W_value
    attention_scores = queries @ keys.T
    attention_weights = torch.softmax(
      attention_scores / keys.shape[-1]**0.5, dim=-1
    )
    context_vec = attention_weights @ values
    return context_vec

In [18]:
torch.manual_seed(123)

d_in = inputs.shape[1]
d_out = 2 
sa_v1 = SelfAttention_v1(d_in, d_out)
print(sa_v1(inputs))

tensor([[0.2996, 0.8053],
        [0.3061, 0.8210],
        [0.3058, 0.8203],
        [0.2948, 0.7939],
        [0.2927, 0.7891],
        [0.2990, 0.8040]], grad_fn=<MmBackward0>)


In [21]:
nn.Parameter(torch.rand(d_in, d_out))

Parameter containing:
tensor([[0.4545, 0.9737],
        [0.4606, 0.5159],
        [0.4220, 0.5786]], requires_grad=True)

In [20]:
class SelfAttention_v2(nn.Module):
    def __init__(self, d_in, d_out, qkv_bias=False):
        super().__init__()
        self.W_query = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_key   = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_value = nn.Linear(d_in, d_out, bias=qkv_bias)

    def forward(self, x):
        keys = self.W_key(x)
        queries = self.W_query(x)
        values = self.W_value(x)
        attn_scores = queries @ keys.T
        attn_weights = torch.softmax(
            attn_scores / keys.shape[-1]**0.5, dim=-1
        )
        context_vec = attn_weights @ values
        return context_vec
    
sa_v2 = SelfAttention_v2(d_in, d_out)
print(sa_v2(inputs))

tensor([[-0.5176, -0.2086],
        [-0.5217, -0.2100],
        [-0.5217, -0.2100],
        [-0.5227, -0.2102],
        [-0.5219, -0.2101],
        [-0.5226, -0.2102]], grad_fn=<MmBackward0>)


In [23]:
nn.Linear(d_in, d_out, bias=False)

Linear(in_features=3, out_features=2, bias=False)

## causal attention

In [30]:
inputs

tensor([[0.4300, 0.1500, 0.8900],
        [0.5500, 0.8700, 0.6600],
        [0.5700, 0.8500, 0.6400],
        [0.2200, 0.5800, 0.3300],
        [0.7700, 0.2500, 0.1000],
        [0.0500, 0.8000, 0.5500]])

In [34]:
queries = sa_v2.W_query(inputs)
keys = sa_v2.W_key(inputs)
attn_scores = queries @ keys.T
attn_weights = torch.softmax(
  attn_scores / keys.shape[-1]**0.5, dim=-1
)
print(attn_weights)

tensor([[0.1741, 0.1564, 0.1565, 0.1733, 0.1690, 0.1708],
        [0.1596, 0.1686, 0.1685, 0.1682, 0.1657, 0.1693],
        [0.1594, 0.1687, 0.1686, 0.1683, 0.1657, 0.1693],
        [0.1618, 0.1693, 0.1692, 0.1665, 0.1658, 0.1674],
        [0.1570, 0.1700, 0.1698, 0.1683, 0.1652, 0.1698],
        [0.1640, 0.1683, 0.1682, 0.1664, 0.1662, 0.1669]],
       grad_fn=<SoftmaxBackward0>)


In [35]:
context_length = attn_scores.shape[0]
mask_simple = torch.tril(torch.ones(context_length, context_length))
print(mask_simple)

tensor([[1., 0., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 1.]])


In [36]:
masked_simple = attn_weights * mask_simple
print(masked_simple)

tensor([[0.1741, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1596, 0.1686, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1594, 0.1687, 0.1686, 0.0000, 0.0000, 0.0000],
        [0.1618, 0.1693, 0.1692, 0.1665, 0.0000, 0.0000],
        [0.1570, 0.1700, 0.1698, 0.1683, 0.1652, 0.0000],
        [0.1640, 0.1683, 0.1682, 0.1664, 0.1662, 0.1669]],
       grad_fn=<MulBackward0>)


In [37]:
# renormalize
masked_simple_norm = masked_simple / masked_simple.sum(dim=-1, keepdim=True)
print(masked_simple_norm)

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.4863, 0.5137, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3208, 0.3397, 0.3395, 0.0000, 0.0000, 0.0000],
        [0.2426, 0.2539, 0.2538, 0.2497, 0.0000, 0.0000],
        [0.1891, 0.2047, 0.2046, 0.2027, 0.1990, 0.0000],
        [0.1640, 0.1683, 0.1682, 0.1664, 0.1662, 0.1669]],
       grad_fn=<DivBackward0>)


In [42]:
# a more efficient way to apply the mask is to set the masked positions to a very large negative number before applying softmax, so that they become zero after softmax. This way we can avoid the need for renormalization.  
mask = torch.triu(torch.ones(context_length, context_length), diagonal=1)
masked = attn_scores.masked_fill(mask.bool(), float('-inf'))
print(masked)

tensor([[-0.1736,    -inf,    -inf,    -inf,    -inf,    -inf],
        [-0.0439,  0.0338,    -inf,    -inf,    -inf,    -inf],
        [-0.0446,  0.0361,  0.0353,    -inf,    -inf,    -inf],
        [ 0.0022,  0.0665,  0.0660,  0.0431,    -inf,    -inf],
        [-0.0457,  0.0669,  0.0658,  0.0526,  0.0267,    -inf],
        [ 0.0065,  0.0428,  0.0424,  0.0267,  0.0248,  0.0312]],
       grad_fn=<MaskedFillBackward0>)


In [43]:
attn_weights = torch.softmax(masked / keys.shape[-1]**0.5, dim=-1)
print(attn_weights)

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.4863, 0.5137, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3208, 0.3397, 0.3395, 0.0000, 0.0000, 0.0000],
        [0.2426, 0.2539, 0.2538, 0.2497, 0.0000, 0.0000],
        [0.1891, 0.2047, 0.2046, 0.2027, 0.1990, 0.0000],
        [0.1640, 0.1683, 0.1682, 0.1664, 0.1662, 0.1669]],
       grad_fn=<SoftmaxBackward0>)


## mask additional weights (dropout)

In [47]:
# example
torch.manual_seed(123)
dropout = torch.nn.Dropout(p=0.5)
example = torch.ones(6, 6)
print(dropout(example))

tensor([[2., 2., 0., 2., 2., 0.],
        [0., 0., 0., 2., 0., 2.],
        [2., 2., 2., 2., 0., 2.],
        [0., 2., 2., 0., 0., 2.],
        [0., 2., 0., 2., 0., 2.],
        [0., 2., 2., 2., 2., 0.]])


In [48]:
# apply dropout to attention weights
print(dropout(attn_weights))

tensor([[2.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.6794, 0.6790, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.5076, 0.4994, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.3980, 0.0000],
        [0.3280, 0.3366, 0.0000, 0.3328, 0.3323, 0.3338]],
       grad_fn=<MulBackward0>)


In [51]:
class CausalAttention(nn.Module):
    def __init__(self, d_in, d_out, context_length,
                dropout, qkv_bias=False):
        super().__init__()
        self.d_out = d_out
        self.W_query = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_key   = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_value = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.dropout = nn.Dropout(dropout)
        self.register_buffer(
           'mask',
           torch.triu(torch.ones(context_length, context_length),
           diagonal=1)
        )

    def forward(self, x):
        b, num_tokens, d_in = x.shape
        keys = self.W_key(x)
        queries = self.W_query(x)
        values = self.W_value(x)

        attn_scores = queries @ keys.transpose(1, 2)   
        attn_scores.masked_fill_(
            self.mask.bool()[:num_tokens, :num_tokens], -torch.inf) 
        attn_weights = torch.softmax(
            attn_scores / keys.shape[-1]**0.5, dim=-1
        )
        attn_weights = self.dropout(attn_weights)

        context_vec = attn_weights @ values
        return context_vec

In [ ]:
# simulate a batch of input token embeddings
batch = torch.stack((inputs, inputs), dim=0)
batch.shape

torch.Size([2, 6, 3])

In [57]:
torch.manual_seed(123)
context_length = batch.shape[1]
ca = CausalAttention(d_in, d_out, context_length, dropout=0.0)
context_vec = ca(batch)
print(context_vec.shape)

torch.Size([2, 6, 2])


## multi-head attention

# 4. implementing GPT from scratch to generate text

# 5. pretraining on unlabeled data

# 6. fine-tuning for classification

# 7. fine-tuning to follow instructions